# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_workflow.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'voice_workflow.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14voice_workflow.proto\x12\x0evoice_workflow\"v\n\rClientMessage\x12-\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x1b.voice_workflow.VoiceConfigH\x00\x12\x15\n\x0b\x61udio_chunk\x18\x02 \x01(\x0cH\x00\x12\x14\n\ntext_input\x18\x03 \x01(\tH\x00\x42\t\n\x07\x63ontent\"M\n\x0bVoiceConfig\x12\x15\n\rlanguage_code\x18\x01 \x01(\t\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x13\n\x0bsample_rate\x18\x03 \x01(\x05\"\x99\x01\n\rServerMessage\x12\x1a\n\x10transcript_chunk\x18\x01 \x01(\tH\x00\x12\x1c\n\x12llm_response_chunk\x18\x02 \x01(\tH\x00\x12\x15\n\x0b\x61udio_chunk\x18\x03 \x01(\x0cH\x00\x12,\n\x05\x65vent\x18\x04 \x01(\x0b\x32\x1b.voice_workflow.ServerEventH\x00\x42\t\n\x07\x63ontent\"G\n\x0bServerEvent\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.voice_workflow.EventType\x12\x0f\n\x07message\x18\x02 \x01(\t*k\n\tEventType\x12\x15\n\x11\x45VENT_UNSPECIFIED\x10\x00\x12\r\n\tLISTENING\x10\x01\x12\x0e\n\nPROCESSING\x10\x02\x12\x0c\n\x08SPEAKING\x10\x03\x12\t\n\x05\x45RROR\x10\x04\x12\x0f\n\x0b\x45ND_OF_TURN\x10\x05\x32_\n\x0cVoiceGateway\x12O\n\x0bStreamAudio\x12\x1d.voice_workflow.ClientMessage\x1a\x1d.voice_workflow.ServerMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_workflow_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTTYPE']._serialized_start=468
  _globals['_EVENTTYPE']._serialized_end=575
  _globals['_CLIENTMESSAGE']._serialized_start=40
  _globals['_CLIENTMESSAGE']._serialized_end=158
  _globals['_VOICECONFIG']._serialized_start=160
  _globals['_VOICECONFIG']._serialized_end=237
  _globals['_SERVERMESSAGE']._serialized_start=240
  _globals['_SERVERMESSAGE']._serialized_end=393
  _globals['_SERVEREVENT']._serialized_start=395
  _globals['_SERVEREVENT']._serialized_end=466
  _globals['_VOICEGATEWAY']._serialized_start=577
  _globals['_VOICEGATEWAY']._serialized_end=672
# @@protoc_insertion_point(module_scope)
